### ISSUE TITLE
Addition of Widgets for User interface

### ISSUE THREAD

**Issue by ptawde95** [greytrix/greytrix-ui-kit#1]
List of widgets  from below Repos :
https://github.com/bhaveshd96196/OMS/
https://github.com/olayemii/flutter-ui-kits

- [x] 1.Tab Widget
- [ ] 2.LineChart Widget
- [ ] 3.PieChart Widget
- [ ] 4.BarChart  Widget
- [x] 5.Mini Card Widget (With Image and Information / Category)
- [ ] 6.Selection card Widget (WIth Icon and Description)
- [x] 7.Product Detail widget with Add to cart and Quantity increase/descrease functionality

**Comment by ptawde95** [comment]
Task[19-04-2021]
Tab Widget
Reference :
![image](https://user-images.githubusercontent.com/47977097/115218779-8825b800-a124-11eb-90b5-68abd651408d.png)

**Comment by ptawde95** [comment]
Task[19-04-2021]
Tab Widget :
![image (3)](https://user-images.githubusercontent.com/47977097/115272634-40228780-a15c-11eb-995b-60c1aa33e9a9.png)

**Comment by SameerChorge94** [comment]
Closed due to inactivity.
