### ISSUE TITLE
Image Saved in background during selfie punch

### ISSUE THREAD

**Issue by nileshgajare** [greytrix/greytrix-ui-kit#47]
Selfie image is getting saved in phone memory.

If we open gallery then all the selfie images which was captured for Punching purpose gets saved automatically.

Same  issue was present in Old App but after client concerns old app was modified accordingly

**Comment by SameerChorge94** [comment]
Closing this issue.
As confirmed from bhushan selfie image are stored in system temporary directory, and those photos are not listed in gallery currently.
